{{- if .Values.dbSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.dbSecret.name }}
  namespace: {{ .Values.namespace | default .Values.name | quote }}
  labels:
    {{- include "rhbk.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  username: {{ .Values.dbSecret.username }}
  password: {{ .Values.dbSecret.password }}
{{- end }}