{{- if and .Values.tlsSecret .Values.tlsSecret.crt }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.http.tlsSecret }}
  namespace: {{ .Values.namespace | default .Values.name | quote }}
  labels:
    {{- include "rhbk.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  tls.crt: {{ .Values.tlsSecret.crt }}
  tls.key: {{ .Values.tlsSecret.key }}
{{- end }}