{{- if not .Values.deployOperator }}
{{- if and .Values.tlsSecret .Values.tlsSecret.servingCert }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}-custom-route
  namespace: {{ .Values.namespace | default .Values.name | quote }}
  labels:
    {{- include "rhbk.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  to:
    kind: Service
    name: {{ .Values.name }}-custom-service
  tls:
    termination: reencrypt
  host: {{ .Values.hostname.hostname }}
  port:
    targetPort: https
{{- end }}
{{- end }}